notifications:
  email: false
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      env: compiler=g++-8 pkg=g++-8
    - os: osx
      osx_image: xcode9.3
      env: compiler=clang++-mp-6.0 pkg=clang-6.0

before_install:
  - source .travis.sh $TRAVIS_OS_NAME conf $pkg >/dev/null
  - mkdir bin

script:
  - $compiler --version
  - source .travis.sh $TRAVIS_OS_NAME build $compiler
  - bin/unit_test
