notifications:
  email: false
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      env: VER=7 CODECOV=1
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: VER=6.0

script:
  - source .travis.sh &>/dev/null
  - $BUILD --version

  - $BUILD $DEBUG -o unit_test $UNIT_TEST/*.cpp
  - ./unit_test
  - if [ "$CODECOV" = 1 ]; then { $COV *.gcno && bash <(curl -s https://codecov.io/bash); } &>/dev/null; fi
