notifications:
  email: false
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      env: compiler=g++-7 options='-std=c++17 -mcx16 -latomic'

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq                                ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install $compiler -yq                     ;fi

script:
  - $compiler --version
  - mkdir bin
  - $compiler -o bin/unit_test test/unit_test/*.cpp $options
  - bin/unit_test
