notifications:
  email: false
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      env: compiler=g++-8
    - os: osx
      osx_image: xcode9.3
      env: compiler=clang++-mp-6.0 pkg=clang-6.0

before_install:
  - conf=travis_ci/conf_$TRAVIS_OS_NAME
  - build=travis_ci/build_$TRAVIS_OS_NAME
  - source $conf >/dev/null
  - mkdir bin

script:
  - $compiler --version
  - source $build
  - bin/unit_test
