notifications:
  email: false
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      env: VER=8
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: VER=6.0

script:
  - source .travis.sh >/dev/null
  - $BUILD --version
  - $BUILD -o unit_test $UNIT_TEST/*.cpp -std=c++17 -mcx16 $EXTRA -Werror -pedantic -pedantic-errors -Wall -Wextra
  - ./unit_test
